spring:
  datasource:
    url: jdbc:h2:mem:orders
    username: sa
    password: password
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        tcpAllowOthers: true
        webPort: 8082


  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.springframework: ERROR
    com.example: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: orders.log

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

local:
  server:
    port: 8081


server:
  error:
    include-message: always
